import Vue from 'vue';
import draggable from 'vuedraggable';
import DatePicker from 'vue2-datepicker';
import 'vue2-datepicker/index.css';
import MButton from '~/components/default/MButton.vue';
import MInput from '~/components/default/MInput.vue';
import MSelect from '~/components/default/MSelect.vue';
import MTabs from '~/components/default/MTabs.vue';
import MUp from '~/components/default/MUp.vue';
import MCounter from '~/components/default/MCounter.vue';
import MPagination from '~/components/default/MPagination.vue';
import Forgot from '~/components/authorization/Forgot.vue';
import Signin from '~/components/authorization/Signin.vue';
import Register from '~/components/authorization/Register.vue';
import UserRegister from '~/components/authorization/UserRegister.vue';
import Terms from '~/components/authorization/Terms.vue';
import Success from '~/components/authorization/Success.vue';
import Reset from '~/components/authorization/Reset.vue';
import SuccessForgot from '~/components/authorization/SuccessForgot.vue';
import SuccessDelete from '~/components/authorization/SuccessDelete.vue';
import SuccessRegister from '~/components/authorization/SuccessRegister.vue';
import SuccessReset from '~/components/authorization/SuccessReset.vue';
import CompanyLogo from '~/components/role/CompanyLogo.vue';
import Document from '~/components/role/Document.vue';
import ImageUpload from '~/components/role/ImageUpload.vue';
import MDialog from '~/components/dialog/MDialog.vue';
import MInfo from '~/components/dialog/MInfo.vue';
import MFeedback from '~/components/dialog/MFeedback.vue';
import MReview from '~/components/dialog/MReview.vue';
import Draft from '~/components/Draft.vue';
import MDraft from '~/components/dialog/MDraft.vue';
import Screen from '~/components/Screen.vue';
import MBreadcrumps from '~/components/default/MBreadcrumps.vue';

Vue.component('m-button', MButton);
Vue.component('m-input', MInput);
Vue.component('m-select', MSelect);
Vue.component('m-tabs', MTabs);
Vue.component('m-up', MUp);
Vue.component('m-counter', MCounter);
Vue.component('m-pagination', MPagination);
Vue.component('forgot', Forgot);
Vue.component('m-info', MInfo);
Vue.component('feedback', MFeedback);
Vue.component('m-review', MReview);
Vue.component('signin', Signin);
Vue.component('register', Register);
Vue.component('user-register', UserRegister);
Vue.component('terms', Terms);
Vue.component('success', Success);
Vue.component('success-forgot', SuccessForgot);
Vue.component('success-register', SuccessRegister);
Vue.component('success-reset', SuccessReset);
Vue.component('success-delete', SuccessDelete);
Vue.component('m-dialog', MDialog);
Vue.component('m-draft', MDraft);
Vue.component('reset', Reset);
Vue.component('c-logo', CompanyLogo);
Vue.component('m-document', Document);
Vue.component('m-image-upload', ImageUpload);
Vue.component('draggable', draggable);
Vue.component('datepicker', DatePicker);
Vue.component('draft', Draft);
Vue.component('screen', Screen);
Vue.component('m-breadcrumps', MBreadcrumps);
